### ISSUE TITLE
[feature request] bash-like "last argument" variable

### ISSUE THREAD

**Issue by sentriz** [alecsammon/kpcli#3]
Hello,  
if it doesn't exist already, a variable, similar to bash's `!$` would be very useful.
normally, it expands to the last argument of the last command.

_bash_ example:

```
$ echo a b c
a b c
$ echo !$
c
```

_kpcli_ example:

```
kpcli:/> xu personal/social/facebook
kpcli:/> xp !$
```

which should be identical to:

```
kpcli:/> xu personal/social/facebook
kpcli:/> xp personal/social/facebook
```

this would make for a much faster workflow when logging into sites.

Thank you,
Senan

**Comment by alecsammon** [comment]
Hi Senan,

This isn't really my repo - sorry. I needed it in a public git repo for machine setup.

You should contact the original source here:  http://kpcli.sourceforge.net/
