### ISSUE TITLE
yubikey keechallenge

### ISSUE THREAD

**Issue by borghal** [alecsammon/kpcli#5]
Hi, it seems kpcli can't open my database. I'm using a yubikey via the keechallenge plugin. Is it possible to include this functionality?

**Comment by alecsammon** [comment]
Hi @borghal 

Sorry - this is not the place to report this. I needed the repository in git to allow me to automate some builds.

I think you need to report this to the original project here: http://kpcli.sourceforge.net/

**Comment by borghal** [comment]
Thank you, will do.
